export const COPY = {
  common: {
    tryAgain: 'Try again',
    appName: 'Movie Explorer',
  },
  tabs: {
    browse: 'Browse',
    favorites: 'Favorites',
    profile: 'Profile',
  },
  navigation: {
    trailer: 'Trailer',
  },
  login: {
    title: 'Sign in',
    submit: 'Log in',
    submitAnonymous: 'Continue as guest',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    emailPlaceholder: 'you@example.com',
    passwordPlaceholder: '••••••••',
    emailRequired: 'Enter your email',
    emailInvalid: 'Enter a valid email address',
    passwordRequired: 'Enter your password',
    passwordTooShort: 'Use at least 6 characters',
  },
  home: {
    title: 'Browse',
    searchPlaceholder: 'Search movies by title',
    hintPopularLead: 'Popular right now',
    hintPopularTrailMore: 'Pull to refresh or scroll for more.',
    hintPopularTrail: 'Pull to refresh for the latest picks.',
    hintTypingLead: 'Still showing popular picks',
    hintTypingTrail: 'Keep typing in the search box to look up a specific film.',
    hintSearching: (q: string) => `Searching for “${q}”…`,
    hintResultsLead: (countLabel: string, q: string) => `${countLabel} for “${q}”`,
    hintResultsTrailMore: 'Scroll for the next page.',
    hintResultsTrailEnd: 'End of results for this search.',
    hintUpdatingResults: 'Updating results…',
    hintFilmCountOne: '1 film',
    hintFilmCountMany: (n: number) => `${n} films`,
    partialTypingOne: 'One more character, then we search.',
    partialTypingMany: (need: number) => `${need} more characters to search by title.`,
    emptyLoadingTitle: 'Loading your picks…',
    emptyLoadingSub: 'Fetching popular films and posters.',
    emptyErrorSearchTitle: 'Search couldn’t finish',
    emptyErrorListTitle: 'Couldn’t load the list',
    emptyErrorSearchSub: 'Check your connection, then pull to refresh.',
    emptyErrorListSub: 'Check your connection, then pull to refresh.',
    emptyTypingTitle: 'Keep typing',
    emptyTypingSubOne: 'Two characters unlock search across the catalog.',
    emptyTypingSubMany: (need: number) => `${need} more characters to search by title.`,
    emptyNoResultsTitle: 'No films match that search',
    emptyNoResultsSub: (q: string) =>
      `Nothing matched “${q}”. Try another title, actor, or a broader keyword — or clear search to browse popular picks.`,
    emptyNothingTitle: 'Nothing to show yet',
    emptyNothingSub: 'Pull down to refresh, or search for something to watch.',
    offlineBanner: 'You’re offline. You may still see what you already loaded until you reconnect.',
    emptyErrorOfflineTitle: 'No connection',
    emptyErrorOfflineSub:
      'Go online to browse films. Anything from this session may still appear until you close the app.',
  },
  favorites: {
    emptyTitle: 'No saved films yet',
    emptySub: 'Open a film and tap Save to add it here.',
  },
  movie: {
    invalid: 'This link isn’t valid.',
    loadError: 'Couldn’t load this film.',
    offlineHint: 'Go online to load this film.',
    stackTitleFallback: 'Film',
    retry: 'Retry',
    saved: 'Saved',
    save: 'Save',
    trailer: 'Trailer',
    noOverview: 'No synopsis yet.',
    releasedLabel: 'Released',
    ratingLabel: 'Rating',
    runtimeLabel: 'Runtime',
    notAvailable: '—',
    ratingValue: (score: number) => `${score.toFixed(1)} / 10`,
    runtimeMinutes: (minutes: number) => `${minutes} min`,
  },
  player: {
    noTrailer: 'No trailer to play.',
    cantPlayTitle: 'Can’t play inside the app',
    watchOnYoutube: 'Watch on YouTube',
    openInBrowser: 'Open in browser',
    youtubeEmbedBlocked:
      'This video can’t be embedded here. Use Watch on YouTube below.',
    youtubeMissing: 'This trailer isn’t available or is private.',
    youtubeHtml5Error:
      'Playback failed in the built-in player. Try opening in the browser.',
    youtubeInvalidId: 'This trailer link looks invalid.',
    youtubeFallback: 'Playback failed. Try Watch on YouTube or try again.',
  },
  profile: {
    appearanceLabel: 'Appearance',
    appearanceHint: 'Follow the system, or lock to light or dark.',
    signedInAs: 'Signed in as',
    guestSession: 'Guest',
    signOut: 'Sign out',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
  },
};
